add_newline = false

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 20
style = "yellow"

[git_status]
conflicted = "[=$count](bold red)"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "[?](red)"
modified = "[!](red)"
staged = "[+](green)"
renamed = "[»](green)"
style = "gray"

[custom.git_user_email]
command = "git config user.email"
description = "The author e-mail for commits"
directories = [".git"]
